# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaBlended_V2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QIcon, QPixmap
import collections

class Ui_Blended(QWidget):
    def __init__(self,directorio):
        self.directorio = directorio

        super().__init__()
        self.setupUi(self)

    def setupUi(self, Grafica):
        Grafica.setObjectName("Grafica")
        Grafica.resize(770, 630)
        self.centralwidget = QtWidgets.QWidget(Grafica)
        self.centralwidget.setObjectName("centralwidget")
        self.V4Frame_IMGS = QtWidgets.QFrame(self.centralwidget)
        self.V4Frame_IMGS.setGeometry(QtCore.QRect(0, 30, 601, 601))
        self.V4Frame_IMGS.setStyleSheet("background-color: rgb(216, 223, 234);")
        self.V4Frame_IMGS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.V4Frame_IMGS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.V4Frame_IMGS.setObjectName("V4Frame_IMGS")
        self.imgB = QtWidgets.QLabel(self.V4Frame_IMGS)
        self.imgB.setGeometry(QtCore.QRect(0, 0, 601, 601))
        self.imgB.setObjectName("imgB")
        self.V4Frame_Datos = QtWidgets.QFrame(self.centralwidget)
        self.V4Frame_Datos.setGeometry(QtCore.QRect(600, 30, 171, 601))
        self.V4Frame_Datos.setStyleSheet("background-color: rgb(216, 223, 234);")
        self.V4Frame_Datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.V4Frame_Datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.V4Frame_Datos.setObjectName("V4Frame_Datos")
        self.V3LabelNSA = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSA.setGeometry(QtCore.QRect(10, 20, 31, 21))
        self.V3LabelNSA.setStyleSheet("background-color: rgb(109,199,42);")
        self.V3LabelNSA.setObjectName("V3LabelNSA")
        self.V3LabelNSE = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSE.setGeometry(QtCore.QRect(10, 50, 31, 21))
        self.V3LabelNSE.setStyleSheet("background-color: rgb(255,236,0);")
        self.V3LabelNSE.setObjectName("V3LabelNSE")
        self.V3LabelNNS = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNS.setGeometry(QtCore.QRect(10, 80, 31, 21))
        self.V3LabelNNS.setStyleSheet("background-color: rgb(251,153,0);")
        self.V3LabelNNS.setObjectName("V3LabelNNS")
        self.V3LabelNNP = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNP.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.V3LabelNNP.setStyleSheet("background-color: rgb(158,158,158);")
        self.V3LabelNNP.setObjectName("V3LabelNNP")
        self.V3LabelNSAC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSAC.setGeometry(QtCore.QRect(10, 140, 41, 21))
        self.V3LabelNSAC.setStyleSheet("background-color: rgb(112,139,39);")
        self.V3LabelNSAC.setObjectName("V3LabelNSAC")
        self.V3LabelNSEC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSEC.setGeometry(QtCore.QRect(10, 170, 41, 21))
        self.V3LabelNSEC.setStyleSheet("background-color: rgb(250,89,1);")
        self.V3LabelNSEC.setObjectName("V3LabelNSEC")
        self.V3LabelNNSC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNSC.setGeometry(QtCore.QRect(10, 200, 41, 21))
        self.V3LabelNNSC.setStyleSheet("background-color: rgb(165,111,9);")
        self.V3LabelNNSC.setObjectName("V3LabelNNSC")
        self.V3LabelNNPC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNPC.setGeometry(QtCore.QRect(10, 230, 41, 21))
        self.V3LabelNNPC.setStyleSheet("background-color: rgb(40,126,140);")
        self.V3LabelNNPC.setObjectName("V3LabelNNPC")
        self.V3LabelPorcentajeBio = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPorcentajeBio.setGeometry(QtCore.QRect(0, 270, 171, 31))
        self.V3LabelPorcentajeBio.setStyleSheet("background-color: rgb(1, 118, 180);\n"
"border:rgb(1, 118, 180);")
        self.V3LabelPorcentajeBio.setObjectName("V3LabelPorcentajeBio")
        self.V3LabelNSA_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSA_N.setGeometry(QtCore.QRect(110, 20, 31, 21))
        self.V3LabelNSA_N.setObjectName("V3LabelNSA_N")
        self.V3LabelNSAC_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSAC_N.setGeometry(QtCore.QRect(110, 140, 31, 20))
        self.V3LabelNSAC_N.setObjectName("V3LabelNSAC_N")
        self.V3LabelNSEC_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSEC_N.setGeometry(QtCore.QRect(110, 170, 31, 21))
        self.V3LabelNSEC_N.setObjectName("V3LabelNSEC_N")
        self.V3LabelNNS_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNS_N.setGeometry(QtCore.QRect(110, 80, 31, 20))
        self.V3LabelNNS_N.setObjectName("V3LabelNNS_N")
        self.V3LabelNNP_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNP_N.setGeometry(QtCore.QRect(110, 110, 31, 20))
        self.V3LabelNNP_N.setObjectName("V3LabelNNP_N")
        self.V3LabelNNSC_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNSC_N.setGeometry(QtCore.QRect(110, 200, 31, 21))
        self.V3LabelNNSC_N.setObjectName("V3LabelNNSC_N")
        self.V3LabelNNPC_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNNPC_N.setGeometry(QtCore.QRect(110, 230, 31, 20))
        self.V3LabelNNPC_N.setObjectName("V3LabelNNPC_N")
        self.V3LabelNSE_N = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelNSE_N.setGeometry(QtCore.QRect(110, 50, 31, 16))
        self.V3LabelNSE_N.setObjectName("V3LabelNSE_N")
        self.V3PBnSE = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnSE.setGeometry(QtCore.QRect(110, 350, 51, 20))
        self.V3PBnSE.setObjectName("V3PBnSE")
        self.V3LabelPBsanaC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBsanaC.setGeometry(QtCore.QRect(10, 410, 41, 21))
        self.V3LabelPBsanaC.setStyleSheet("background-color: rgb(112,139,39);")
        self.V3LabelPBsanaC.setObjectName("V3LabelPBsanaC")
        self.V3PBnSAC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnSAC.setGeometry(QtCore.QRect(110, 410, 51, 20))
        self.V3PBnSAC.setObjectName("V3PBnSAC")
        self.V3LabelPBsecaC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBsecaC.setGeometry(QtCore.QRect(10, 440, 41, 21))
        self.V3LabelPBsecaC.setStyleSheet("background-color: rgb(250,89,1);")
        self.V3LabelPBsecaC.setObjectName("V3LabelPBsecaC")
        self.V3PBnSA = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnSA.setGeometry(QtCore.QRect(110, 320, 51, 21))
        self.V3PBnSA.setObjectName("V3PBnSA")
        self.V3LabelPBns = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBns.setGeometry(QtCore.QRect(10, 380, 31, 21))
        self.V3LabelPBns.setStyleSheet("background-color: rgb(251,153,0);")
        self.V3LabelPBns.setObjectName("V3LabelPBns")
        self.V3LabelPBnsc = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBnsc.setGeometry(QtCore.QRect(10, 470, 41, 21))
        self.V3LabelPBnsc.setStyleSheet("background-color: rgb(165,111,9);")
        self.V3LabelPBnsc.setObjectName("V3LabelPBnsc")
        self.V3PBnNS = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnNS.setGeometry(QtCore.QRect(110, 380, 51, 20))
        self.V3PBnNS.setObjectName("V3PBnNS")
        self.V3PBnSEC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnSEC.setGeometry(QtCore.QRect(110, 440, 51, 20))
        self.V3PBnSEC.setObjectName("V3PBnSEC")
        self.V3LabelPBsana = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBsana.setGeometry(QtCore.QRect(10, 320, 31, 21))
        self.V3LabelPBsana.setStyleSheet("background-color: rgb(109,199,42);")
        self.V3LabelPBsana.setObjectName("V3LabelPBsana")
        self.V3LabelPBseca = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBseca.setGeometry(QtCore.QRect(10, 350, 31, 21))
        self.V3LabelPBseca.setStyleSheet("background-color: rgb(255,236,0);")
        self.V3LabelPBseca.setObjectName("V3LabelPBseca")
        self.V3PBnNSC = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3PBnNSC.setGeometry(QtCore.QRect(110, 470, 51, 20))
        self.V3PBnNSC.setObjectName("V3PBnNSC")
        self.V3LabelPBT = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBT.setGeometry(QtCore.QRect(10, 530, 91, 16))
        self.V3LabelPBT.setObjectName("V3LabelPBT")
        self.V3LabelPBnT = QtWidgets.QLabel(self.V4Frame_Datos)
        self.V3LabelPBnT.setGeometry(QtCore.QRect(110, 530, 51, 16))
        self.V3LabelPBnT.setObjectName("V3LabelPBnT")
        self.V3FrameEt1 = QtWidgets.QFrame(self.centralwidget)
        self.V3FrameEt1.setGeometry(QtCore.QRect(0, 0, 601, 31))
        self.V3FrameEt1.setStyleSheet("background-color: rgb(1, 118, 180);\n"
"border:rgb(1, 118, 180);")
        self.V3FrameEt1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.V3FrameEt1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.V3FrameEt1.setObjectName("V3FrameEt1")
        self.V3LabeGrafica = QtWidgets.QLabel(self.V3FrameEt1)
        self.V3LabeGrafica.setGeometry(QtCore.QRect(210, 10, 181, 20))
        self.V3LabeGrafica.setObjectName("V3LabeGrafica")
        self.V3FrameEt2 = QtWidgets.QFrame(self.centralwidget)
        self.V3FrameEt2.setGeometry(QtCore.QRect(600, 0, 171, 31))
        self.V3FrameEt2.setStyleSheet("background-color: rgb(1, 118, 180);\n"
"border:rgb(1, 118, 180);")
        self.V3FrameEt2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.V3FrameEt2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.V3FrameEt2.setObjectName("V3FrameEt2")
        self.V3LabeVuelo = QtWidgets.QLabel(self.V3FrameEt2)
        self.V3LabeVuelo.setGeometry(QtCore.QRect(0, -1, 171, 31))
        self.V3LabeVuelo.setObjectName("V3LabeVuelo")
        #Grafica.setCentralWidget(self.centralwidget)

        self.retranslateUi(Grafica)
        QtCore.QMetaObject.connectSlotsByName(Grafica)

    def retranslateUi(self, Grafica):
        _translate = QtCore.QCoreApplication.translate
        Grafica.setWindowTitle(_translate("Grafica", "Data"))
        self.imgB.setText(_translate("Grafica", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; color:#ffffff;\">Click on a color box.</span></p></body></html>"))
        self.V3LabelNSA.setText(_translate("Grafica", "H:"))
        self.V3LabelNSE.setText(_translate("Grafica", "D:"))
        self.V3LabelNNS.setText(_translate("Grafica", "UNH:"))
        self.V3LabelNNP.setText(_translate("Grafica", "NV:"))
        self.V3LabelNSAC.setText(_translate("Grafica", "HC:"))
        self.V3LabelNSEC.setText(_translate("Grafica", "DC:"))
        self.V3LabelNNSC.setText(_translate("Grafica", "UNHC:"))
        self.V3LabelNNPC.setText(_translate("Grafica", "NVC:"))
        self.V3LabelPorcentajeBio.setText(_translate("Grafica", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Percent of biomass</span></p></body></html>"))
        self.V3LabelNSA_N.setText(_translate("Grafica", "225"))
        self.V3LabelNSAC_N.setText(_translate("Grafica", "11"))
        self.V3LabelNSEC_N.setText(_translate("Grafica", "18"))
        self.V3LabelNNS_N.setText(_translate("Grafica", "10"))
        self.V3LabelNNP_N.setText(_translate("Grafica", "10"))
        self.V3LabelNNSC_N.setText(_translate("Grafica", "20"))
        self.V3LabelNNPC_N.setText(_translate("Grafica", "15"))
        self.V3LabelNSE_N.setText(_translate("Grafica", "20"))
        self.V3PBnSE.setText(_translate("Grafica", "20 %"))
        self.V3LabelPBsanaC.setText(_translate("Grafica", "HC:"))
        self.V3PBnSAC.setText(_translate("Grafica", "10 %"))
        self.V3LabelPBsecaC.setText(_translate("Grafica", "DC:"))
        self.V3PBnSA.setText(_translate("Grafica", "80 %"))
        self.V3LabelPBns.setText(_translate("Grafica", "UNH:"))
        self.V3LabelPBnsc.setText(_translate("Grafica", "UNHC:"))
        self.V3PBnNS.setText(_translate("Grafica", "10 %"))
        self.V3PBnSEC.setText(_translate("Grafica", "11 %"))
        self.V3LabelPBsana.setText(_translate("Grafica", "H:"))
        self.V3LabelPBseca.setText(_translate("Grafica", "D:"))
        self.V3PBnNSC.setText(_translate("Grafica", "18 %"))
        self.V3LabelPBT.setText(_translate("Grafica", "Biomass Total:"))
        self.V3LabelPBnT.setText(_translate("Grafica", "40 %"))
        self.V3LabeGrafica.setText(_translate("Grafica", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Result of the analysis</span></p></body></html>"))
        self.V3LabeVuelo.setText(_translate("Grafica", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Imaga data</span></p></body></html>"))


        
    def actualiza(self,imgBig,Tags,F_vh):
        pixmapB = QPixmap(self.directorio+'ImgsBlended/'+imgBig+'_blended.JPG')
        if F_vh=='NO' or F_vh =='SE':
            self.imgB.setGeometry(QtCore.QRect(0, 75, 600, 450))
            pixmapB = pixmapB.scaled(600, 450)
        else: 
            self.imgB.setGeometry(QtCore.QRect(75, 0, 450, 600))
            pixmapB = pixmapB.scaled(450, 600)
        counter = collections.Counter(Tags)
        total = 0
        print(counter)
        for k,v in counter.items():
            total = total + v
        _translate = QtCore.QCoreApplication.translate
        self.V3LabelNSA_N.setText(_translate("Grafica", str(counter[0])))
        self.V3LabelNSE_N.setText(_translate("Grafica", str(counter[1])))
        self.V3LabelNNS_N.setText(_translate("Grafica", str(counter[2])))
        self.V3LabelNNP_N.setText(_translate("Grafica", str(counter[3])))
        self.V3LabelNSAC_N.setText(_translate("Grafica", str(counter[4])))
        self.V3LabelNSEC_N.setText(_translate("Grafica", str(counter[5])))
        self.V3LabelNNSC_N.setText(_translate("Grafica", str(counter[6])))
        self.V3LabelNNPC_N.setText(_translate("Grafica", str(counter[7])))

        self.V3PBnSA.setText(_translate("Grafica", str("{0:.2f} %".format((counter[0]*100)/total))))#"{0:.2f}".format(self.paramBio[0])
        self.V3PBnSE.setText(_translate("Grafica", str("{0:.2f} %".format((counter[1]*100)/total))))
        self.V3PBnNS.setText(_translate("Grafica", str("{0:.2f} %".format((counter[2]*100)/total))))
        self.V3PBnSAC.setText(_translate("Grafica", str("{0:.2f} %".format((counter[4]*100)/total))))
        self.V3PBnSEC.setText(_translate("Grafica", str("{0:.2f} %".format((counter[5]*100)/total))))
        self.V3PBnNSC.setText(_translate("Grafica", str("{0:.2f} %".format((counter[6]*100)/total))))
        totalb = ((counter[0]*100)/total)+((counter[1]*100)/total)+((counter[2]*100)/total)+((counter[4]*100)/total)+((counter[5]*100)/total)+((counter[6]*100)/total)
        self.V3LabelPBnT.setText(_translate("Grafica", str("{0:.2f} %".format((totalb*100)/total))))
        self.imgB.setPixmap(pixmapB)


